export enum POKEMON {
  GET_LIST_REQUEST = "POKEMON/GET_LIST/REQUEST",
  GET_LIST_SUCCESS = "POKEMON/GET_LIST/SUCCESS",
  GET_LIST_FAILURE = "POKEMON/GET_LIST/FAILURE",
  GET_REQUEST = "POKEMON/GET/REQUEST",
  GET_SUCCESS = "POKEMON/GET/SUCCESS",
  GET_FAILURE = "POKEMON/GET/FAILURE",
}
